<?xml version="1.0"?>
<robot name="simple_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassisHeight" value="0.2"/>
  <xacro:property name="chassisLength" value="0.6"/>
  <xacro:property name="chassisWidth" value="0.4"/>
  <xacro:property name="chassisMass" value="30"/>

  <xacro:property name="casterRadius" value="0.05"/>
  <xacro:property name="casterMass" value="5"/>

  <xacro:property name="wheelWidth" value="0.05"/>
  <xacro:property name="wheelRadius" value="0.1"/>
  <xacro:property name="wheelPos" value="0.2"/>
  <xacro:property name="wheelMass" value="5"/>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
   </xacro:macro>
  <xacro:macro name="box_inertia" params="m x y z">
     <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0" iyy="${m*(x*x+z*z)/12}" iyz="0" izz="${m*(x*x+z*z)/12}"/>
  </xacro:macro>
  <xacro:macro name="sphere_inertia" params="m r">
     <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0" iyy="${2*m*r*r/5}" iyz="0" izz="${2*m*r*r/5}"/>
  </xacro:macro>
  <xacro:macro name="default_inertial">
    <inertial>
      <mass value="0.01" />
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
    </inertial>
  </xacro:macro>

  <xacro:include filename="$(find simple_robot_description)/urdf/materials.urdf.xacro"/>
  <xacro:include filename="$(find simple_robot_description)/urdf/sr.gazebo"/>
  <xacro:include filename="$(find simple_robot_description)/urdf/common.xacro"/>
  <robotBaseFrame>mobile_base_link</robotBaseFrame>

  <link name="mobile_base_link">
    <visual>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${chassisHeight/2+wheelRadius/2}"/>
      <material name="Schunk/DarkGolden"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 ${chassisHeight/2+wheelRadius/2}"/>
      <geometry>
        <box size="${chassisLength} ${chassisWidth} ${chassisHeight}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassisMass}"/>
      <origin rpy="0 0 0" xyz="0 0 ${chassisHeight/2+wheelRadius/2}"/>
      <xacro:box_inertia m="${chassisMass}" x="${chassisLength}" y="${chassisWidth}" z="${chassisHeight}"/>
    </inertial>
  <!--castor-->
  <visual >
      <origin xyz="-0.2 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
      <material name="Schunk/DarkGolden"/>
  </visual>
  <collision name='castor_front_collision'>
      <origin xyz="-0.2 0 0" rpy="0 0 0" />
      <geometry>
        <sphere radius="${casterRadius}"/>
      </geometry>
  </collision>
  <inertial>
      <mass value="${casterMass}"/>
      <origin rpy="0 0 0" xyz="-0.2 0 0"/>
      <xacro:sphere_inertia m="${casterMass}" r="${casterRadius}"/>
    </inertial>
  </link>

  <link name="mobile_dummy_link">
  </link>
  <joint name="mobile_dummy_joint" type="fixed">
    <parent link="mobile_base_link"/>
    <child link="mobile_dummy_link"/>
    <origin xyz="0 0 0"/>
  </joint>

<!--link of right wheel" /-->
  <link name="wheel_right_link">
    <visual>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <material name="Schunk/Black"/>
    </visual>
    <collision>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheelMass}"/>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
    </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="mobile_base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.2 0.226 0.05"/>
    <axis xyz="0 1 0"/>
    <limit effort="100.0" velocity="100"/>
    <dynamics damping="0.0" friction="0.0" />
  </joint>

<!--link of left wheel" /-->
  <link name="wheel_left_link">
    <visual>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <material name="Schunk/Black"/>
    </visual>
    <collision>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheelMass}"/>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <xacro:cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="mobile_base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.2 -0.226 0.05"/>
    <axis xyz="0 1 0"/>
    <limit effort="100.0" velocity="100"/>
    <dynamics damping="0.0" friction="0.0" />
  </joint>

<!--link of front wheel" />
  <link name="mobile_vor_wheel">
    <visual>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Schunk/DarkGrey"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.1"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_to_vor_wheel" type="continuous">
    <parent link="mobile_base_link"/>
    <child link="mobile_vor_wheel"/>
    <origin xyz="-0.2 0 0.05"/>
  </joint-->


  <link name="arm_base_link">
   <visual>
      <geometry>
        <cylinder length="0.05" radius="0.1"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Schunk/DarkGolden"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="0.1"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->
  </link>

  <!-- joint between base_link and lwa4p_extended_connector_link -->
  <joint name="arm_base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.1 0 0.275"/>
    <parent link="mobile_base_link"/>
    <child link="arm_base_link"/>
  </joint>

  <!-- link 1 -->
  <link name="arm_1_link">
   <visual>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Schunk/DarkGrey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->

  </link>

  <!-- joint 1 between base_link and arm_1_link -->
  <joint name="arm_1_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 0 0.045"/>
    <parent link="arm_base_link"/>
    <child link="arm_1_link"/>
    <axis xyz="0 0 1"/>
    <limit effort="370" lower="-3.14" upper="3.14" velocity="1.26"/>
  </joint>

  <!-- link 2 -->
  <link name="arm_2_link">
   <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <!--<xacro:default_inertial/>-->
    <inertial>
      <mass value="0.01"/>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>

    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.32"/>
      <geometry>
        <box size="0.04 0.04 0.6"/>
      </geometry>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.32"/>
      <geometry>
        <box size="0.04 0.04 0.6"/>
      </geometry>
    </collision>
    <!--<xacro:default_inertial/>-->
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0.32"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>

   <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0.64"/>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0.64"/>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <!--<xacro:default_inertial/>-->
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0.64"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>

  </link>
  <!-- joint 2 between arm_1_link and arm_2_link-->
  <joint name="arm_2_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 -0.04 0"/>
    <parent link="arm_1_link"/>
    <child link="arm_2_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="370" lower="-1.57" upper="1.57" velocity="1.26"/>
    <safety_controller k_position="20" k_velocity="50" soft_lower_limit="-6.27" soft_upper_limit="6.27" />
  </joint>

  <!-- link 3 -->
  <link name="arm_3_link">
   <visual>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Schunk/DarkGrey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->

  </link>
  <!-- joint 3 between link 2 and link3 -->
  <joint name="arm_3_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 0.04 0.64"/>
    <parent link="arm_2_link"/>
    <child link="arm_3_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="370" lower="-2.65" upper="2.65" velocity="1.26"/>
    <safety_controller k_position="20" k_velocity="50" soft_lower_limit="-6.27" soft_upper_limit="6.27" />
  </joint>

  <!-- link 4 -->
  <link name="arm_4_link">
   <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->

    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.22"/>
      <geometry>
        <box size="0.04 0.04 0.4"/>
      </geometry>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.22"/>
      <geometry>
        <box size="0.04 0.04 0.4"/>
      </geometry>
    </collision>
    <!--<xacro:default_inertial/>-->
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0.22"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>

   <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0.44"/>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0.44"/>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <!--<xacro:default_inertial/>-->
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 ${PI/2} 0" xyz="0 0 0.44"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>

  </link>
  <!-- joint 4 between arm_3_link and arm_4_link-->
  <joint name="arm_4_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0.04 0.0 0.0"/>
    <parent link="arm_3_link"/>
    <child link="arm_4_link"/>
    <axis xyz="1 0 0"/>
    <limit effort="370" lower="-2.65" upper="2.65" velocity="1.26"/>
    <safety_controller k_position="20" k_velocity="50" soft_lower_limit="-6.27" soft_upper_limit="6.27" />
  </joint>

  <!-- link 5 -->
  <link name="arm_5_link">
   <visual>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Schunk/DarkGrey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->

  </link>
  <!-- joint 5 between link 3 and link4 -->
  <joint name="arm_5_joint" type="revolute">
    <origin rpy="0 0 0" xyz="-0.04 0 0.44"/>
    <parent link="arm_4_link"/>
    <child link="arm_5_link"/>
    <axis xyz="1 0 0"/>
    <limit effort="370" lower="-3.14" upper="3.14" velocity="1.26"/>
    <safety_controller k_position="20" k_velocity="50" soft_lower_limit="-6.27" soft_upper_limit="6.27" />
  </joint>

  <!-- link 6 -->
  <link name="arm_6_link">
   <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->

    <visual>
      <origin rpy="0 0 0" xyz="0 0 0.12"/>
      <geometry>
        <box size="0.04 0.04 0.2"/>
      </geometry>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.12"/>
      <geometry>
        <box size="0.04 0.04 0.2"/>
      </geometry>
    </collision>
    <!--<xacro:default_inertial/>-->
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0.12"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>

   <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0.24"/>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0.24"/>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <!--<xacro:default_inertial/>-->
    <inertial>
      <mass value="0.01"/>
      <origin rpy="${PI/2} 0 0" xyz="0 0 0.24"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>

  </link>
  <!-- joint 6 between arm_5_link and arm_6_link-->
  <joint name="arm_6_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 -0.04 0.0"/>
    <parent link="arm_5_link"/>
    <child link="arm_6_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="370" lower="-3.14" upper="3.14" velocity="1.26"/>
    <safety_controller k_position="20" k_velocity="50" soft_lower_limit="-6.27" soft_upper_limit="6.27" />
  </joint>

  <!-- link 7 -->
  <link name="arm_7_link">
   <visual>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Schunk/DarkGrey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->

  </link>
  <!-- joint 7 between link 3 and link4 -->
  <joint name="arm_7_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 0.04 0.24"/>
    <parent link="arm_6_link"/>
    <child link="arm_7_link"/>
    <axis xyz="0 1 0"/>
    <limit effort="370" lower="-3.14" upper="3.14" velocity="1.26"/>
    <safety_controller k_position="20" k_velocity="50" soft_lower_limit="-6.27" soft_upper_limit="6.27" />
  </joint>

  <!-- link 8 ee -->
  <link name="arm_8_link">
   <visual>
      <geometry>
        <cylinder length="0.06" radius="0.02"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <material name="Schunk/Blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <xacro:default_inertial/>
    <!--<inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>-->
  </link>

  <!-- joint 8 ee between arm_7_link and arm_8_link-->
  <joint name="arm_8_joint" type="revolute">
    <origin rpy="0 0 0" xyz="0 0.0 0.04"/>
    <parent link="arm_7_link"/>
    <child link="arm_8_link"/>
    <axis xyz="0 0 1"/>
    <limit effort="370" lower="-0.7" upper="0.7" velocity="1.26"/>
    <safety_controller k_position="20" k_velocity="50" soft_lower_limit="-6.27" soft_upper_limit="6.27" />
  </joint>


</robot>
